version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: benchmark-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: benchmark-test
      PGDATA: /data/postgres
    networks:
      - benchmark-test-db-network
    ports:
      - "5431:5432"
    restart: always
networks:
  benchmark-test-db-network:
    driver: bridge