spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/benchmark-test
    username: admin
    password: password
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5434/benchmark-test
    user: admin
    password: password
server:
  port: 8080
