spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5431/benchmark-test
    username: admin
    password: password
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5431/benchmark-test
    user: admin
    password: password
server:
  port: 8080
